<form id="opc-discount-coupon-form" action="<?php echo $this->getUrl('checkout/cart/couponPost', array('_secure' => $this->getRequest()->isSecure())) ?>" method="post">
    <div class="discount">
        <div class="discount-form">
            <label for="coupon_code"><?php echo $this->__('Enter your coupon code:') ?></label>            
            <div class="input-box">
                <input class="input-text" id="coupon_code" type="text" name="coupon_code" value="<?php echo $this->htmlEscape($this->getCouponCode()) ?>" autocomplete="off"/>
            </div>
            <div class="buttons-set">
                <button type="button" title="<?php echo $this->__('Apply') ?>" class="button apply-coupon btn solid__btn solid__blue__btn text-uppercase"  value="<?php echo $this->__('Apply') ?>"><?php echo $this->__('Apply') ?></button>
                <?php if(strlen($this->getCouponCode())): ?>
                    &nbsp; <button type="button" title="<?php echo $this->__('Cancel') ?>" class="button remove-coupon right btn solid__btn text-uppercase"  value="<?php echo $this->__('Cancel') ?>"><?php echo $this->__('Cancel') ?></button>
                <?php endif;?>
            </div>
        </div>
    </div>
</form>