<script type="text/javascript">
    var clevertap = {event:[], profile:[], account:[], enum:function(e){return '$E_' + e}};
    var account_id="<?php echo (string)Mage::getStoreConfig('clevertap_options/general/id')?>";
    clevertap.account.push({"id": account_id});
    (function () {
        var wzrk = document.createElement('script');
        wzrk.type = 'text/javascript';
        wzrk.async = true;
        wzrk.src = ('https:' == document.location.protocol ? 'https://d2r1yp2w7bby2u.cloudfront.net' : 'http://static.clevertap.com') + '/js/a.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wzrk, s);
    })();
</script>