<?php  
/**
 * @extension   Remmote_Facebookpixelremarketing
 * @author      Remmote    
 * @copyright   2016 - Remmote.com
 * @descripion  Pixel code template
 */
?>

<!-- Facebook Pixel Code - Remmote © -->
<script> 
	!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod? 
	n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n; 
	n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0; 
	t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window, 
	document,'script','//connect.facebook.net/en_US/fbevents.js');

	<?php
		$pixel_id 	 	 = $this->getPixelId();
	?>

	fbq('init',  '<?php echo $pixel_id ?>'); 
	fbq('track', 'PageView');

	<?php
	//Stardand events
	echo $this->getViewContentEvent();
	echo $this->getSearchEvent();
	echo $this->getAddToCartEvent();
	echo $this->getAddToWishlistEvent();
	echo $this->getInitiateCheckoutEvent();
	echo $this->getAddPaymentInfoEvent();
	echo $this->getPurchaseEvent();
	echo $this->getLeadEvent();
	echo $this->getCompleteRegistrationEvent();
	?>

</script> 
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=<?php echo $pixel_id?>&ev=PageView&noscript=1"
/></noscript>
<!-- End Facebook Pixel Code - Remmote © -->