<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<?php if($meta_title=$this->getMetaTitle()): ?>
<title><?php echo htmlspecialchars($meta_title) ?></title>
<?php else: ?>
<meta name="google-site-verification" content="qPoPWAVmXtkruzkyh8iIBFI4l8FiIYuY_WsAfudJgCk" />
<title><?php echo $this->getTitle() ?></title>
<?php endif; ?>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="p:domain_verify" content="af8faa2e1d762e24199a41e54aa2c1fd"/>
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />

<?php
    $theme = Mage::helper('porto');
    $charSubset = '&subset=latin';
    $d = $theme->getCfgSectionDesign();
    $s = $theme->getCfgSectionSettings();
	if(!isset($s['general']['disable_responsive']) || (isset($s['general']['disable_responsive']) && !$s['general']['disable_responsive'])){
?>	
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<?php
	}
?>
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="author" href="https://plus.google.com/+TheMomsCoindia" />
<link rel="publisher" href="https://plus.google.com/+TheMomsCoindia" />


<?php
$groupId = Mage::app()->getStore()->getGroupId();
$collection = Mage::getModel('core/store')->getCollection()->addFieldToFilter('group_id', $groupId);
foreach ($collection as $store) {
        echo '<link rel="alternate" href="' . preg_replace('/\?.*/', '', $store->getCurrentUrl()) . '" hreflang="' . $store->getCode().'-in' . '"/>' . "\n";
        }
?>


<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WJW54T2');</script>
<!-- End Google Tag Manager -->

<?php //Include Google fonts character subsets (such as extended latin, cyrillic)
    if (isset($d['font']['primary_char_latin_ext']) && $d['font']['primary_char_latin_ext']==1 )
        $charSubset .= ',latin-ext';
    if (isset($d['font']['custom_char_subset']) && $d['font']['custom_char_subset'])
        $charSubset .= ','.$d['font']['custom_char_subset'];
    $font_sizes = "%3A300%2C300italic%2C400%2C400italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic";
?>
<?php if ($d['font']['custom'] && $d['font']['primary_font_family_group'] == 'google'): ?>
<link rel="stylesheet" href='//fonts.googleapis.com/css?family=<?php echo str_replace(' ', '+', $d['font']['primary_font_family']).$font_sizes; echo $charSubset; ?>' type='text/css' />
<?php else: ?>
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans%3A300%2C300italic%2C400%2C400italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic&amp;v1&amp;subset=latin%2Clatin-ext" type="text/css" media="screen"/>
<?php endif;?>
<link href='//fonts.googleapis.com/css?family=Shadows+Into+Light' rel='stylesheet' type='text/css'/>
<?php echo $this->getCssJsHtml() ?>

<!--
  Add this snippet into <head> tag in app/design/frontend/FOO/BAR/template/page/html/head.phtml
  Modified from http://naileditdesign.com/facebook-open-graph-meta-tags-in-magento/
  + Added Category image
-->

<?php /* Open Graph Protocol for Facebook and SEO START */ ?>
<?php if(Mage::registry('current_product')): ?>
<?php $product = Mage::registry('current_product'); ?>
<meta property="og:title" content="<?php echo ($product->getName()); ?>" />
<meta property="og:type" content="product" />
<meta property="og:image" content="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(200,200);?>" />
<meta property="og:url" content="<?php echo Mage::registry('product')->getProductUrl(); ?>" />
<meta property="og:description" content="<?php echo strip_tags(($product->getShortDescription())); ?>" />
<meta property="og:site_name" content="<?php echo Mage::app()->getStore()->getName(); ?>" />
<?php elseif(Mage::registry('current_category')): ?>
<?php $category = Mage::registry('current_category'); ?>
<meta property="og:title" content="<?php echo $this->getTitle() ?>" />
<meta property="og:type" content="product.group" />
<meta property="og:image" content="<?php echo $category->getImageUrl(); ?>" />
<meta property="og:url" content="<?php echo $this->helper('core/url')->getCurrentUrl();?>" />
<meta property="og:description" content="<?php echo strip_tags($this->getDescription()) ?>" />
<meta property="og:site_name" content="<?php echo Mage::app()->getStore()->getName(); ?>" />
<?php elseif((Mage::getSingleton('cms/page')->getIdentifier() == 'home' &&
Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms')) : ?>
<meta property="og:title" content="<?php echo $this->getTitle() ?>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<?php echo $this->helper('core/url')->getCurrentUrl();?>" />
<meta property="og:description" content="<?php echo strip_tags($this->getDescription()) ?>" />
<meta property="og:site_name" content="<?php echo Mage::app()->getStore()->getName(); ?>" />
<?php else: ?>
<meta property="og:title" content="<?php echo $this->getTitle() ?>" />
<meta property="og:type" content="article" />
<meta property="og:url" content="<?php echo $this->helper('core/url')->getCurrentUrl();?>" />
<meta property="og:description" content="<?php echo strip_tags($this->getDescription()) ?>" />
<meta property="og:site_name" content="<?php echo Mage::app()->getStore()->getName(); ?>" />
<?php endif; ?>
<?php /* Open Graph Protocol for Facebook and SEO END */ ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>
<script type="text/javascript">
//<![CDATA[
if (typeof dailydealTimeCountersCategory == 'undefined') {
	var dailydealTimeCountersCategory = new Array();
	var i = 0;
}
//]]>
</script>
<script>
function init() {
var imgDefer = document.getElementsByTagName('img');
for (var i=0; i<imgDefer.length; i++) {
if(imgDefer[i].getAttribute('data-src')) {
imgDefer[i].setAttribute('src',imgDefer[i].getAttribute('data-src'));
} } }
window.onload = init;
</script>
<?php
$currentUrl = Mage::helper('core/url')->getCurrentUrl();
$url = Mage::getSingleton('core/url')->parseUrl($currentUrl);
$path = $url->getPath();
if($path == "/customer/account/login")
{
?>
<script type="text/javascript">
	 jQuery(document).ready(function(){
			jQuery(".ajaxlogin-login")[0].click()
		});
</script>
<?php	
}
?>
<style>
.fbmessenger{
  position:fixed;
  bottom:15px;
  right:15px;
  z-index:15;
}

.fbmessenger img{
  width:50px;
 filter: drop-shadow(2px 6px 4px rgba(0,0,0,.3));
-webkit-filter: drop-shadow(2px 6px 4px rgba(0,0,0,.3));


}
 
.tooltiptext {
    width: 120px;
    background-color: white;
    color:#2c2c2c; ;
    text-align: center;
    padding: 5px 0;
    border:1px solid #eeeeee;
    border-radius: 6px;
    position: fixed;
    bottom:30px;
	right:75px;
  font-family:'abel';
  text-transform:uppercase;
 filter: drop-shadow(2px 6px 4px rgba(0,0,0,.3));
-webkit-filter: drop-shadow(2px 6px 4px rgba(0,0,0,.3));

    
}
  
.tooltiptext:after {
    content: "";
    position: absolute;
    top: 50%;
    left: 100%;
    margin-top: -5px;
    border-width: 5px;
    border-style: solid;
    border-color: transparent transparent transparent #eeeeee;
}
</style>